{
 "title": "Migration Dashboard",
 "time": { "from": "2026-03-10T18:51:30.116Z", "to": "2026-03-10T19:22:14.326Z" },
 "panels": [
  {
   "title": "VM Migration State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (value)(kubevirt_vmi_migration_succeeded {pod=~\"virt-controller-.*\"})",
     "legendFormat": "succeeded"
    },
    {
     "expr": "sum by (value)(kubevirt_vmi_migrations_in_pending_phase {pod=~\"virt-controller-.*\"})",
     "legendFormat": "pending"
    },
    {
     "expr": "sum by (value)(kubevirt_vmi_migrations_in_running_phase {pod=~\"virt-controller-.*\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum by (value)(kubevirt_vmi_migrations_in_scheduling_phase {pod=~\"virt-controller-.*\"})",
     "legendFormat": "scheduling"
    }
   ]
  },
  {
   "title": "VM Migration State",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kubevirt_vmi_migration_phase_transition_time_from_creation_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Migration Time (All VMs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (name,namespace) (kubevirt_vmi_migration_end_time_seconds)  - sum by (name,namespace) (kubevirt_vmi_migration_start_time_seconds) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Migration Time (seconds)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(sum by (name,namespace) (kubevirt_vmi_migration_end_time_seconds)) - min(sum by (name,namespace) (kubevirt_vmi_migration_start_time_seconds))",
     "legendFormat": "Total Duration"
    },
    {
     "expr": "max(sum by (name,namespace) (kubevirt_vmi_migration_end_time_seconds) - sum by (name,namespace) (kubevirt_vmi_migration_start_time_seconds))",
     "legendFormat": "max time (VMs)"
    },
    {
     "expr": "avg(sum by (name,namespace) (kubevirt_vmi_migration_end_time_seconds) - sum by (name,namespace) (kubevirt_vmi_migration_start_time_seconds))",
     "legendFormat": "average time (VMs)"
    },
    {
     "expr": "min(sum by (name,namespace) (kubevirt_vmi_migration_end_time_seconds) - sum by (name,namespace) (kubevirt_vmi_migration_start_time_seconds))",
     "legendFormat": "min time (VMs)"
    }
   ]
  },
  {
   "title": "Migration - data processed |  remaining",
   "type": "timeseries",
   "description": "kubevirt_vmi_migration_data_processed_bytes: The total Guest OS data processed and migrated to the new VM.\nkubevirt_vmi_migration_data_remaining_bytes: The remaining guest OS data to be migrated to the new VM.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kubevirt_vmi_migration_data_processed_bytes)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (kubevirt_vmi_migration_data_remaining_bytes)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (kubevirt_vmi_migration_data_total_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Migration - data processing rate/VM",
   "type": "timeseries",
   "description": "kubevirt_vmi_migration_data_processed_bytes: The total Guest OS data processed and migrated to the new VM.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate (kubevirt_vmi_migration_data_processed_bytes[1m])",
     "legendFormat": "{{namespace}}-{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage - Top 10 (openshift-cnv | openshift-migration)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "topk(10,sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"openshift-cnv|openshift-migration\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage - Top 10 (openshift-cnv | openshift-migration)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(10,sum(container_memory_working_set_bytes{ cluster=\"\", namespace=~\"openshift-cnv|openshift-migration\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "bandwidth by Host - Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum by(instance) (rate(node_network_receive_bytes_total{device=~\"(eth|en).*\"}[1m]) * on(instance, device) node_network_info{operstate=\"up\"})) +\n(sum by(instance) (rate(node_network_transmit_bytes_total{device=~\"(eth|en).*\"}[1m]) * on(instance, device) node_network_info{operstate=\"up\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "bandwidth by Host - iscsi",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum by(instance) (rate(node_network_receive_bytes_total{device=\"ens1f0\"}[1m]) * on(instance, device) node_network_info{operstate=\"up\"})) +\n(sum by(instance) (rate(node_network_transmit_bytes_total{device=\"ens1f0\"}[1m]) * on(instance, device) node_network_info{operstate=\"up\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "bandwidth by Host - podnet",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum by(instance) (rate(node_network_receive_bytes_total{device=\"ens1f1\"}[1m]) * on(instance, device) node_network_info{operstate=\"up\"})) +\n(sum by(instance) (rate(node_network_transmit_bytes_total{device=\"ens1f1\"}[1m]) * on(instance, device) node_network_info{operstate=\"up\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "bandwidth by Host - multus bridge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum by(instance) (rate(node_network_receive_bytes_total{device=\"ens2f0np0\"}[1m]) * on(instance, device) node_network_info{operstate=\"up\"})) +\n(sum by(instance) (rate(node_network_transmit_bytes_total{device=\"ens2f0np0\"}[1m]) * on(instance, device) node_network_info{operstate=\"up\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "migration_memory_transfer_rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "kubevirt_vmi_migration_memory_transfer_rate_bytes",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "kubevirt_vmi_migration_dirty_memory_rate_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(kubevirt_vmi_network_receive_bytes_total [1m])",
     "legendFormat": "{{kubernetes_vmi_label_kubevirt_io_domain}}-rx"
    },
    {
     "expr": "-rate(kubevirt_vmi_network_transmit_bytes_total [1m])",
     "legendFormat": "{{kubernetes_vmi_label_kubevirt_io_domain}}-tx"
    }
   ]
  },
  {
   "title": "CPU Usage - Top 10 (migration-vms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "topk(10,sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"simple-fio\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage - Top 10 (migration-vms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(10,sum(container_memory_working_set_bytes{ cluster=\"\", namespace=~\"simple-fio\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}